image: julia:1.5                # image comes from Docker hub

before_script:
  - python3 -m pip install --user matplotlib
  - julia --project=@. -e "import Pkg; Pkg.build()"

default:
  script:
    - julia --project=@. -e "import Pkg; Pkg.test()"

